/* Auto-generated by scripts/write-public-config.mjs — do not edit by hand. */
export const publicConfig = {
  apiUrl: "http://localhost:5080",
  hubUrl: "http://localhost:5080/hubs/chat",
  keycloakAuthority: "http://localhost:8080/realms/vibechat",
  keycloakClientId: "vibechat-web",
  grafanaUrl: "http://localhost:3000",
  enableDevAuth: false,
} as const;
