#!/bin/bash
# Creates migrator / app / backup PostgreSQL roles (SEC-RLS-RUNTIME / ADR-009).
# Idempotent. Passwords are DEMO values from .env — never production secrets.
set -euo pipefail

POSTGRES_APP_USER="${POSTGRES_APP_USER:-vibechat_app}"
POSTGRES_APP_PASSWORD="${POSTGRES_APP_PASSWORD:-vibechat_app_password_change_me}"
POSTGRES_MIGRATOR_USER="${POSTGRES_MIGRATOR_USER:-vibechat_migrator}"
POSTGRES_MIGRATOR_PASSWORD="${POSTGRES_MIGRATOR_PASSWORD:-vibechat_migrator_password_change_me}"
POSTGRES_BACKUP_USER="${POSTGRES_BACKUP_USER:-vibechat_backup}"
POSTGRES_BACKUP_PASSWORD="${POSTGRES_BACKUP_PASSWORD:-vibechat_backup_password_change_me}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_MIGRATOR_USER}') THEN
      CREATE ROLE ${POSTGRES_MIGRATOR_USER} LOGIN PASSWORD '${POSTGRES_MIGRATOR_PASSWORD}' BYPASSRLS;
    ELSE
      ALTER ROLE ${POSTGRES_MIGRATOR_USER} WITH LOGIN BYPASSRLS PASSWORD '${POSTGRES_MIGRATOR_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_APP_USER}') THEN
      CREATE ROLE ${POSTGRES_APP_USER} LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    ELSE
      ALTER ROLE ${POSTGRES_APP_USER} WITH LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD '${POSTGRES_APP_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_BACKUP_USER}') THEN
      CREATE ROLE ${POSTGRES_BACKUP_USER} LOGIN PASSWORD '${POSTGRES_BACKUP_PASSWORD}' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    ELSE
      ALTER ROLE ${POSTGRES_BACKUP_USER} WITH LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD '${POSTGRES_BACKUP_PASSWORD}';
    END IF;
  END
  \$\$;

  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_MIGRATOR_USER}, ${POSTGRES_APP_USER}, ${POSTGRES_BACKUP_USER};
  GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_MIGRATOR_USER};
  GRANT ${POSTGRES_MIGRATOR_USER} TO ${POSTGRES_USER};
EOSQL

echo "PostgreSQL roles ready: ${POSTGRES_MIGRATOR_USER}, ${POSTGRES_APP_USER}, ${POSTGRES_BACKUP_USER}."
