import { Injectable, inject } from '@angular/core';
import { ProfileApiService } from './profile-api.service';
import { DirectoryApiService } from './directory-api.service';
import { MessagingApiService } from './messaging-api.service';
import { FilesApiService } from './files-api.service';
import { AdminApiService } from './admin-api.service';
import { NotificationsApiService } from './notifications-api.service';
import { SearchApiService } from './search-api.service';
import { AiApiService } from './ai-api.service';
import { ImportApiService } from './import-api.service';

export type { AppearancePreference, MeProfile } from './profile-api.service';
export type { ChannelMessagesPage } from './messaging-api.service';

@Injectable({ providedIn: 'root' })
export class ApiService {
  private readonly profile = inject(ProfileApiService);
  private readonly directory = inject(DirectoryApiService);
  private readonly messaging = inject(MessagingApiService);
  private readonly files = inject(FilesApiService);
  private readonly admin = inject(AdminApiService);
  private readonly notifications = inject(NotificationsApiService);
  private readonly search = inject(SearchApiService);
  private readonly ai = inject(AiApiService);
  private readonly imports = inject(ImportApiService);

  readonly getMe: ProfileApiService['getMe'] = this.profile.getMe.bind(this.profile);
  readonly updateMe: ProfileApiService['updateMe'] = this.profile.updateMe.bind(this.profile);
  readonly getMemberProfile: ProfileApiService['getMemberProfile'] = this.profile.getMemberProfile.bind(this.profile);
  readonly updateMemberProfile: ProfileApiService['updateMemberProfile'] = this.profile.updateMemberProfile.bind(this.profile);
  readonly uploadAvatar: ProfileApiService['uploadAvatar'] = this.profile.uploadAvatar.bind(this.profile);
  readonly deleteAvatar: ProfileApiService['deleteAvatar'] = this.profile.deleteAvatar.bind(this.profile);
  readonly fetchAvatar: ProfileApiService['fetchAvatar'] = this.profile.fetchAvatar.bind(this.profile);
  readonly updateAppearance: ProfileApiService['updateAppearance'] = this.profile.updateAppearance.bind(this.profile);
  readonly getWorkspaces: DirectoryApiService['getWorkspaces'] = this.directory.getWorkspaces.bind(this.directory);
  readonly getSpaces: DirectoryApiService['getSpaces'] = this.directory.getSpaces.bind(this.directory);
  readonly createSpace: DirectoryApiService['createSpace'] = this.directory.createSpace.bind(this.directory);
  readonly getChannels: DirectoryApiService['getChannels'] = this.directory.getChannels.bind(this.directory);
  readonly createChannel: DirectoryApiService['createChannel'] = this.directory.createChannel.bind(this.directory);
  readonly updateChannelTopic: DirectoryApiService['updateChannelTopic'] = this.directory.updateChannelTopic.bind(this.directory);
  readonly getCommands: DirectoryApiService['getCommands'] = this.directory.getCommands.bind(this.directory);
  readonly getMembers: DirectoryApiService['getMembers'] = this.directory.getMembers.bind(this.directory);
  readonly getContactGroups: DirectoryApiService['getContactGroups'] = this.directory.getContactGroups.bind(this.directory);
  readonly createContactGroup: DirectoryApiService['createContactGroup'] = this.directory.createContactGroup.bind(this.directory);
  readonly updateContactGroup: DirectoryApiService['updateContactGroup'] = this.directory.updateContactGroup.bind(this.directory);
  readonly deleteContactGroup: DirectoryApiService['deleteContactGroup'] = this.directory.deleteContactGroup.bind(this.directory);
  readonly replaceContactGroupMembers: DirectoryApiService['replaceContactGroupMembers'] = this.directory.replaceContactGroupMembers.bind(this.directory);
  readonly getGroupedContacts: DirectoryApiService['getGroupedContacts'] = this.directory.getGroupedContacts.bind(this.directory);
  readonly getAssignableRoles: DirectoryApiService['getAssignableRoles'] = this.directory.getAssignableRoles.bind(this.directory);
  readonly updateMemberRole: DirectoryApiService['updateMemberRole'] = this.directory.updateMemberRole.bind(this.directory);
  readonly inviteMember: DirectoryApiService['inviteMember'] = this.directory.inviteMember.bind(this.directory);
  readonly getPresence: DirectoryApiService['getPresence'] = this.directory.getPresence.bind(this.directory);
  readonly getMyStatus: DirectoryApiService['getMyStatus'] = this.directory.getMyStatus.bind(this.directory);
  readonly setMyStatus: DirectoryApiService['setMyStatus'] = this.directory.setMyStatus.bind(this.directory);
  readonly clearMyStatus: DirectoryApiService['clearMyStatus'] = this.directory.clearMyStatus.bind(this.directory);
  readonly getWorkspaceAvailability: DirectoryApiService['getWorkspaceAvailability'] = this.directory.getWorkspaceAvailability.bind(this.directory);
  readonly reportUserStatus: DirectoryApiService['reportUserStatus'] = this.directory.reportUserStatus.bind(this.directory);
  readonly clearMemberStatus: DirectoryApiService['clearMemberStatus'] = this.directory.clearMemberStatus.bind(this.directory);
  readonly openDirectMessage: DirectoryApiService['openDirectMessage'] = this.directory.openDirectMessage.bind(this.directory);
  readonly openGroupDm: DirectoryApiService['openGroupDm'] = this.directory.openGroupDm.bind(this.directory);
  readonly addGroupDmParticipants: DirectoryApiService['addGroupDmParticipants'] = this.directory.addGroupDmParticipants.bind(this.directory);
  readonly leaveGroupDm: DirectoryApiService['leaveGroupDm'] = this.directory.leaveGroupDm.bind(this.directory);
  readonly renameGroupDm: DirectoryApiService['renameGroupDm'] = this.directory.renameGroupDm.bind(this.directory);
  readonly getChannelMembers: DirectoryApiService['getChannelMembers'] = this.directory.getChannelMembers.bind(this.directory);
  readonly getChannelRoster: DirectoryApiService['getChannelRoster'] = this.directory.getChannelRoster.bind(this.directory);
  readonly addChannelMember: DirectoryApiService['addChannelMember'] = this.directory.addChannelMember.bind(this.directory);
  readonly removeChannelMember: DirectoryApiService['removeChannelMember'] = this.directory.removeChannelMember.bind(this.directory);
  readonly leaveChannel: DirectoryApiService['leaveChannel'] = this.directory.leaveChannel.bind(this.directory);
  readonly createChannelInvite: DirectoryApiService['createChannelInvite'] = this.directory.createChannelInvite.bind(this.directory);
  readonly acceptChannelInvite: DirectoryApiService['acceptChannelInvite'] = this.directory.acceptChannelInvite.bind(this.directory);
  readonly getMessages: MessagingApiService['getMessages'] = this.messaging.getMessages.bind(this.messaging);
  readonly sendMessage: MessagingApiService['sendMessage'] = this.messaging.sendMessage.bind(this.messaging);
  readonly createPoll: MessagingApiService['createPoll'] = this.messaging.createPoll.bind(this.messaging);
  readonly votePoll: MessagingApiService['votePoll'] = this.messaging.votePoll.bind(this.messaging);
  readonly unvotePoll: MessagingApiService['unvotePoll'] = this.messaging.unvotePoll.bind(this.messaging);
  readonly closePoll: MessagingApiService['closePoll'] = this.messaging.closePoll.bind(this.messaging);
  readonly forwardMessage: MessagingApiService['forwardMessage'] = this.messaging.forwardMessage.bind(this.messaging);
  readonly openThread: MessagingApiService['openThread'] = this.messaging.openThread.bind(this.messaging);
  readonly getThread: MessagingApiService['getThread'] = this.messaging.getThread.bind(this.messaging);
  readonly getThreadMessages: MessagingApiService['getThreadMessages'] = this.messaging.getThreadMessages.bind(this.messaging);
  readonly sendThreadMessage: MessagingApiService['sendThreadMessage'] = this.messaging.sendThreadMessage.bind(this.messaging);
  readonly followThread: MessagingApiService['followThread'] = this.messaging.followThread.bind(this.messaging);
  readonly unfollowThread: MessagingApiService['unfollowThread'] = this.messaging.unfollowThread.bind(this.messaging);
  readonly markThreadRead: MessagingApiService['markThreadRead'] = this.messaging.markThreadRead.bind(this.messaging);
  readonly getFollowedThreads: MessagingApiService['getFollowedThreads'] = this.messaging.getFollowedThreads.bind(this.messaging);
  readonly shareThreadReplyToChannel: MessagingApiService['shareThreadReplyToChannel'] = this.messaging.shareThreadReplyToChannel.bind(this.messaging);
  readonly setChannelFollowAllThreads: MessagingApiService['setChannelFollowAllThreads'] = this.messaging.setChannelFollowAllThreads.bind(this.messaging);
  readonly deleteMessageLinkPreview: MessagingApiService['deleteMessageLinkPreview'] = this.messaging.deleteMessageLinkPreview.bind(this.messaging);
  readonly getMessagingPolicy: MessagingApiService['getMessagingPolicy'] = this.messaging.getMessagingPolicy.bind(this.messaging);
  readonly editMessage: MessagingApiService['editMessage'] = this.messaging.editMessage.bind(this.messaging);
  readonly deleteMessage: MessagingApiService['deleteMessage'] = this.messaging.deleteMessage.bind(this.messaging);
  readonly pinMessage: MessagingApiService['pinMessage'] = this.messaging.pinMessage.bind(this.messaging);
  readonly unpinMessage: MessagingApiService['unpinMessage'] = this.messaging.unpinMessage.bind(this.messaging);
  readonly getPins: MessagingApiService['getPins'] = this.messaging.getPins.bind(this.messaging);
  readonly saveMessage: MessagingApiService['saveMessage'] = this.messaging.saveMessage.bind(this.messaging);
  readonly patchSavedMessage: MessagingApiService['patchSavedMessage'] = this.messaging.patchSavedMessage.bind(this.messaging);
  readonly unsaveMessage: MessagingApiService['unsaveMessage'] = this.messaging.unsaveMessage.bind(this.messaging);
  readonly getSavedMessages: MessagingApiService['getSavedMessages'] = this.messaging.getSavedMessages.bind(this.messaging);
  readonly createScheduledMessage: MessagingApiService['createScheduledMessage'] = this.messaging.createScheduledMessage.bind(this.messaging);
  readonly updateScheduledMessage: MessagingApiService['updateScheduledMessage'] = this.messaging.updateScheduledMessage.bind(this.messaging);
  readonly cancelScheduledMessage: MessagingApiService['cancelScheduledMessage'] = this.messaging.cancelScheduledMessage.bind(this.messaging);
  readonly getSchedule: MessagingApiService['getSchedule'] = this.messaging.getSchedule.bind(this.messaging);
  readonly createReminder: MessagingApiService['createReminder'] = this.messaging.createReminder.bind(this.messaging);
  readonly updateReminder: MessagingApiService['updateReminder'] = this.messaging.updateReminder.bind(this.messaging);
  readonly cancelReminder: MessagingApiService['cancelReminder'] = this.messaging.cancelReminder.bind(this.messaging);
  readonly toggleReaction: MessagingApiService['toggleReaction'] = this.messaging.toggleReaction.bind(this.messaging);
  readonly getReactionUsers: MessagingApiService['getReactionUsers'] = this.messaging.getReactionUsers.bind(this.messaging);
  readonly upsertReadCursor: MessagingApiService['upsertReadCursor'] = this.messaging.upsertReadCursor.bind(this.messaging);
  readonly getWorkspaceChannelUnreads: MessagingApiService['getWorkspaceChannelUnreads'] = this.messaging.getWorkspaceChannelUnreads.bind(this.messaging);
  readonly getUnreadCount: MessagingApiService['getUnreadCount'] = this.messaging.getUnreadCount.bind(this.messaging);
  readonly acknowledgeAnnouncement: MessagingApiService['acknowledgeAnnouncement'] = this.messaging.acknowledgeAnnouncement.bind(this.messaging);
  readonly closeAnnouncement: MessagingApiService['closeAnnouncement'] = this.messaging.closeAnnouncement.bind(this.messaging);
  readonly getAnnouncementReport: MessagingApiService['getAnnouncementReport'] = this.messaging.getAnnouncementReport.bind(this.messaging);
  readonly getPendingAnnouncements: MessagingApiService['getPendingAnnouncements'] = this.messaging.getPendingAnnouncements.bind(this.messaging);
  readonly initiateAttachmentUpload: FilesApiService['initiateAttachmentUpload'] = this.files.initiateAttachmentUpload.bind(this.files);
  readonly completeAttachmentUpload: FilesApiService['completeAttachmentUpload'] = this.files.completeAttachmentUpload.bind(this.files);
  readonly transcribeAttachment: FilesApiService['transcribeAttachment'] = this.files.transcribeAttachment.bind(this.files);
  readonly getAttachmentDownload: FilesApiService['getAttachmentDownload'] = this.files.getAttachmentDownload.bind(this.files);
  readonly getAttachmentThumbnail: FilesApiService['getAttachmentThumbnail'] = this.files.getAttachmentThumbnail.bind(this.files);
  readonly getLinkPreviewImage: FilesApiService['getLinkPreviewImage'] = this.files.getLinkPreviewImage.bind(this.files);
  readonly uploadFileToPresignedUrl: FilesApiService['uploadFileToPresignedUrl'] = this.files.uploadFileToPresignedUrl.bind(this.files);
  readonly listInstalledPlugins: AdminApiService['listInstalledPlugins'] = this.admin.listInstalledPlugins.bind(this.admin);
  readonly installPlugin: AdminApiService['installPlugin'] = this.admin.installPlugin.bind(this.admin);
  readonly updateInstalledPlugin: AdminApiService['updateInstalledPlugin'] = this.admin.updateInstalledPlugin.bind(this.admin);
  readonly uninstallPlugin: AdminApiService['uninstallPlugin'] = this.admin.uninstallPlugin.bind(this.admin);
  readonly rotateInstalledPlugin: AdminApiService['rotateInstalledPlugin'] = this.admin.rotateInstalledPlugin.bind(this.admin);
  readonly listWorkspaceTemplates: AdminApiService['listWorkspaceTemplates'] = this.admin.listWorkspaceTemplates.bind(this.admin);
  readonly previewWorkspaceTemplate: AdminApiService['previewWorkspaceTemplate'] = this.admin.previewWorkspaceTemplate.bind(this.admin);
  readonly applyWorkspaceTemplate: AdminApiService['applyWorkspaceTemplate'] = this.admin.applyWorkspaceTemplate.bind(this.admin);
  readonly exportWorkspaceTemplate: AdminApiService['exportWorkspaceTemplate'] = this.admin.exportWorkspaceTemplate.bind(this.admin);
  readonly getOnboarding: AdminApiService['getOnboarding'] = this.admin.getOnboarding.bind(this.admin);
  readonly updateOnboarding: AdminApiService['updateOnboarding'] = this.admin.updateOnboarding.bind(this.admin);
  readonly listIntegrationBots: AdminApiService['listIntegrationBots'] = this.admin.listIntegrationBots.bind(this.admin);
  readonly createIntegrationBot: AdminApiService['createIntegrationBot'] = this.admin.createIntegrationBot.bind(this.admin);
  readonly updateIntegrationBot: AdminApiService['updateIntegrationBot'] = this.admin.updateIntegrationBot.bind(this.admin);
  readonly rotateIntegrationBot: AdminApiService['rotateIntegrationBot'] = this.admin.rotateIntegrationBot.bind(this.admin);
  readonly revokeIntegrationBot: AdminApiService['revokeIntegrationBot'] = this.admin.revokeIntegrationBot.bind(this.admin);
  readonly getAdminStats: AdminApiService['getAdminStats'] = this.admin.getAdminStats.bind(this.admin);
  readonly getAdminAuditEvents: AdminApiService['getAdminAuditEvents'] = this.admin.getAdminAuditEvents.bind(this.admin);
  readonly getAdminConversations: AdminApiService['getAdminConversations'] = this.admin.getAdminConversations.bind(this.admin);
  readonly getAdminConversationMessages: AdminApiService['getAdminConversationMessages'] = this.admin.getAdminConversationMessages.bind(this.admin);
  readonly getAdminThreadMessages: AdminApiService['getAdminThreadMessages'] = this.admin.getAdminThreadMessages.bind(this.admin);
  readonly getAdminSensitiveSettings: AdminApiService['getAdminSensitiveSettings'] = this.admin.getAdminSensitiveSettings.bind(this.admin);
  readonly updateAdminSensitiveSettings: AdminApiService['updateAdminSensitiveSettings'] = this.admin.updateAdminSensitiveSettings.bind(this.admin);
  readonly rotateAdminOpenRouterCredential: AdminApiService['rotateAdminOpenRouterCredential'] = this.admin.rotateAdminOpenRouterCredential.bind(this.admin);
  readonly rotateAdminSmtpCredential: AdminApiService['rotateAdminSmtpCredential'] = this.admin.rotateAdminSmtpCredential.bind(this.admin);
  readonly rotateAdminWebhookCredential: AdminApiService['rotateAdminWebhookCredential'] = this.admin.rotateAdminWebhookCredential.bind(this.admin);
  readonly createAdminWebhook: AdminApiService['createAdminWebhook'] = this.admin.createAdminWebhook.bind(this.admin);
  readonly updateAdminWebhook: AdminApiService['updateAdminWebhook'] = this.admin.updateAdminWebhook.bind(this.admin);
  readonly deleteAdminWebhook: AdminApiService['deleteAdminWebhook'] = this.admin.deleteAdminWebhook.bind(this.admin);
  readonly rotateAdminWebhookEndpoint: AdminApiService['rotateAdminWebhookEndpoint'] = this.admin.rotateAdminWebhookEndpoint.bind(this.admin);
  readonly testAdminWebhook: AdminApiService['testAdminWebhook'] = this.admin.testAdminWebhook.bind(this.admin);
  readonly rotateAdminVapidCredential: AdminApiService['rotateAdminVapidCredential'] = this.admin.rotateAdminVapidCredential.bind(this.admin);
  readonly reencryptAdminSettings: AdminApiService['reencryptAdminSettings'] = this.admin.reencryptAdminSettings.bind(this.admin);
  readonly downloadWorkspaceExport: AdminApiService['downloadWorkspaceExport'] = this.admin.downloadWorkspaceExport.bind(this.admin);
  readonly getPushPublicKey: NotificationsApiService['getPushPublicKey'] = this.notifications.getPushPublicKey.bind(this.notifications);
  readonly listPushSubscriptions: NotificationsApiService['listPushSubscriptions'] = this.notifications.listPushSubscriptions.bind(this.notifications);
  readonly registerPushSubscription: NotificationsApiService['registerPushSubscription'] = this.notifications.registerPushSubscription.bind(this.notifications);
  readonly deletePushSubscription: NotificationsApiService['deletePushSubscription'] = this.notifications.deletePushSubscription.bind(this.notifications);
  readonly getNotificationPreferences: NotificationsApiService['getNotificationPreferences'] = this.notifications.getNotificationPreferences.bind(this.notifications);
  readonly updateNotificationPreferences: NotificationsApiService['updateNotificationPreferences'] = this.notifications.updateNotificationPreferences.bind(this.notifications);
  readonly muteChannelNotifications: NotificationsApiService['muteChannelNotifications'] = this.notifications.muteChannelNotifications.bind(this.notifications);
  readonly clearChannelNotificationOverride: NotificationsApiService['clearChannelNotificationOverride'] = this.notifications.clearChannelNotificationOverride.bind(this.notifications);
  readonly searchMessages: SearchApiService['searchMessages'] = this.search.searchMessages.bind(this.search);
  readonly summarizeChannel: AiApiService['summarizeChannel'] = this.ai.summarizeChannel.bind(this.ai);
  readonly suggestChannelReply: AiApiService['suggestChannelReply'] = this.ai.suggestChannelReply.bind(this.ai);
  readonly createImport: ImportApiService['createImport'] = this.imports.createImport.bind(this.imports);
  readonly getImport: ImportApiService['getImport'] = this.imports.getImport.bind(this.imports);
  readonly planImport: ImportApiService['planImport'] = this.imports.planImport.bind(this.imports);
  readonly executeImport: ImportApiService['executeImport'] = this.imports.executeImport.bind(this.imports);
  readonly pauseImport: ImportApiService['pauseImport'] = this.imports.pauseImport.bind(this.imports);
  readonly resumeImport: ImportApiService['resumeImport'] = this.imports.resumeImport.bind(this.imports);
  readonly publishImport: ImportApiService['publishImport'] = this.imports.publishImport.bind(this.imports);
  readonly rollbackImport: ImportApiService['rollbackImport'] = this.imports.rollbackImport.bind(this.imports);
}
