// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeChat.Infrastructure;

#nullable disable

namespace VibeChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VibeChatDbContext))]
    partial class VibeChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeChat.AI.AiSettings", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkspaceId");

                    b.ToTable("settings", "ai");
                });

            modelBuilder.Entity("VibeChat.AI.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("usage_records", "ai");
                });

            modelBuilder.Entity("VibeChat.Administration.ProcessSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkPreviewEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LinkPreviewTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<bool>("MessageRetentionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("OpenRouterBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RetentionBatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionDefaultDays")
                        .HasColumnType("integer");

                    b.Property<int>("RetentionIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VapidPublicKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VapidSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("process_settings", "administration");
                });

            modelBuilder.Entity("VibeChat.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("audit_events", "audit");
                });

            modelBuilder.Entity("VibeChat.BuildingBlocks.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("outbox_messages", "building_blocks");
                });

            modelBuilder.Entity("VibeChat.BuildingBlocks.TenantRateLimitSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("HubPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("SendPerMinute")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.ToTable("rate_limit_settings", "building_blocks");
                });

            modelBuilder.Entity("VibeChat.Conversations.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParticipantSetKey")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Topic")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId");

                    b.HasIndex("TenantId", "WorkspaceId", "ParticipantSetKey")
                        .IsUnique()
                        .HasFilter("\"ParticipantSetKey\" IS NOT NULL");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("channels", "conversations");
                });

            modelBuilder.Entity("VibeChat.Conversations.ChannelMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("JoinedSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LeftSeq")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("channel_members", "conversations");
                });

            modelBuilder.Entity("VibeChat.Directory.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Order");

                    b.ToTable("spaces", "directory");
                });

            modelBuilder.Entity("VibeChat.Files.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("File");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ThumbnailStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Waveform")
                        .HasColumnType("jsonb");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey");

                    b.HasIndex("TenantId", "ChannelId", "MessageId");

                    b.ToTable("attachments", "files");
                });

            modelBuilder.Entity("VibeChat.Files.TenantFilesSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedContentTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("AudioMaxDurationMs")
                        .HasColumnType("integer");

                    b.Property<long>("AudioMaxSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxAttachmentsPerMessage")
                        .HasColumnType("integer");

                    b.Property<long>("MaxSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("PresignDownloadTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PresignUploadTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId")
                        .HasName("PK_files_settings");

                    b.ToTable("settings", "files");
                });

            modelBuilder.Entity("VibeChat.Identity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("user_profiles", "identity");
                });

            modelBuilder.Entity("VibeChat.Integrations.OutboundWebhookEndpoint", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Secret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("TenantId");

                    b.ToTable("webhook_endpoints", "integrations");
                });

            modelBuilder.Entity("VibeChat.Messaging.ConversationSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "ConversationId");

                    b.ToTable("conversation_sequences", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("idempotency", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.LinkPreview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(480)
                        .HasColumnType("character varying(480)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ImageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SiteName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UrlHash")
                        .IsUnique();

                    b.ToTable("link_previews", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForwardedFromChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForwardedFromMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ForwardedFromMessageId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.HasIndex("TenantId", "ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_tenant_channel_created");

                    b.ToTable("messages", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.MessageLinkPreview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LinkPreviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LinkPreviewId");

                    b.HasIndex("TenantId", "MessageId");

                    b.ToTable("message_link_previews", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.MessageMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("MentionedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MessageId");

                    b.HasIndex("TenantId", "ChannelId", "MentionedUserId");

                    b.ToTable("message_mentions", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.MessageRetentionSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.ToTable("message_retention_settings", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.MessageThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ChannelId");

                    b.HasIndex("TenantId", "ParentMessageId")
                        .IsUnique();

                    b.ToTable("threads", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.PinnedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PinnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PinnedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ChannelId");

                    b.HasIndex("TenantId", "ChannelId", "MessageId")
                        .IsUnique();

                    b.ToTable("pinned_messages", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.Poll", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("boolean");

                    b.Property<bool>("Anonymous")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("TenantId", "ChannelId");

                    b.HasIndex("TenantId", "ClosedAt", "ClosesAt");

                    b.ToTable("polls", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PollId", "Position")
                        .IsUnique();

                    b.ToTable("poll_options", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.PollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PollId", "OptionId", "UserId")
                        .IsUnique();

                    b.ToTable("poll_votes", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "MessageId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("reactions", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.ReadCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastReadSequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("read_cursors", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.SavedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "MessageId")
                        .IsUnique();

                    b.HasIndex("TenantId", "UserId", "CompletedAt", "CreatedAt");

                    b.ToTable("saved_messages", "messaging");
                });

            modelBuilder.Entity("VibeChat.Messaging.TenantLinkPreviewSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.ToTable("link_preview_settings", "messaging");
                });

            modelBuilder.Entity("VibeChat.Notifications.ChannelNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("MutedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("channel_preferences", "notifications");
                });

            modelBuilder.Entity("VibeChat.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DigestEnabled")
                        .HasColumnType("boolean");

                    b.Property<short>("DndDays")
                        .HasColumnType("smallint");

                    b.Property<bool>("DndEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("DndEnd")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DndStart")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("HidePreview")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<Guid[]>("PriorityContactUserIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("preferences", "notifications");
                });

            modelBuilder.Entity("VibeChat.Notifications.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("push_subscriptions", "notifications");
                });

            modelBuilder.Entity("VibeChat.Notifications.TenantEmailSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseStartTls")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TenantId");

                    b.ToTable("email_settings", "notifications");
                });

            modelBuilder.Entity("VibeChat.Tenancy.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("workspaces", "tenancy");
                });

            modelBuilder.Entity("VibeChat.Tenancy.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("workspace_members", "tenancy");
                });

            modelBuilder.Entity("VibeChat.AI.AiSettings", b =>
                {
                    b.OwnsOne("VibeChat.SharedKernel.EncryptedSecretEnvelope", "OpenRouterApiKey", b1 =>
                        {
                            b1.Property<Guid>("AiSettingsWorkspaceId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .HasColumnType("bytea")
                                .HasColumnName("OpenRouterApiKeyCiphertext");

                            b1.Property<short?>("FormatVersion")
                                .HasColumnType("smallint")
                                .HasColumnName("OpenRouterApiKeyFormatVersion");

                            b1.Property<int?>("KeyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("OpenRouterApiKeyKeyVersion");

                            b1.Property<string>("MaskSuffix")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("OpenRouterApiKeyMaskSuffix");

                            b1.Property<byte[]>("Nonce")
                                .HasColumnType("bytea")
                                .HasColumnName("OpenRouterApiKeyNonce");

                            b1.Property<DateTimeOffset?>("RotatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("OpenRouterApiKeyRotatedAt");

                            b1.Property<byte[]>("Tag")
                                .HasColumnType("bytea")
                                .HasColumnName("OpenRouterApiKeyTag");

                            b1.HasKey("AiSettingsWorkspaceId");

                            b1.ToTable("settings", "ai");

                            b1.WithOwner()
                                .HasForeignKey("AiSettingsWorkspaceId");
                        });

                    b.Navigation("OpenRouterApiKey")
                        .IsRequired();
                });

            modelBuilder.Entity("VibeChat.Administration.ProcessSettings", b =>
                {
                    b.OwnsOne("VibeChat.SharedKernel.EncryptedSecretEnvelope", "VapidPrivateKey", b1 =>
                        {
                            b1.Property<int>("ProcessSettingsId")
                                .HasColumnType("integer");

                            b1.Property<byte[]>("Ciphertext")
                                .HasColumnType("bytea")
                                .HasColumnName("VapidPrivateKeyCiphertext");

                            b1.Property<short?>("FormatVersion")
                                .HasColumnType("smallint")
                                .HasColumnName("VapidPrivateKeyFormatVersion");

                            b1.Property<int?>("KeyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("VapidPrivateKeyKeyVersion");

                            b1.Property<string>("MaskSuffix")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("VapidPrivateKeyMaskSuffix");

                            b1.Property<byte[]>("Nonce")
                                .HasColumnType("bytea")
                                .HasColumnName("VapidPrivateKeyNonce");

                            b1.Property<DateTimeOffset?>("RotatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("VapidPrivateKeyRotatedAt");

                            b1.Property<byte[]>("Tag")
                                .HasColumnType("bytea")
                                .HasColumnName("VapidPrivateKeyTag");

                            b1.HasKey("ProcessSettingsId");

                            b1.ToTable("process_settings", "administration");

                            b1.WithOwner()
                                .HasForeignKey("ProcessSettingsId");
                        });

                    b.Navigation("VapidPrivateKey")
                        .IsRequired();
                });

            modelBuilder.Entity("VibeChat.Integrations.OutboundWebhookEndpoint", b =>
                {
                    b.OwnsOne("VibeChat.SharedKernel.EncryptedSecretEnvelope", "SigningSecret", b1 =>
                        {
                            b1.Property<Guid>("OutboundWebhookEndpointTenantId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .HasColumnType("bytea")
                                .HasColumnName("SigningSecretCiphertext");

                            b1.Property<short?>("FormatVersion")
                                .HasColumnType("smallint")
                                .HasColumnName("SigningSecretFormatVersion");

                            b1.Property<int?>("KeyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("SigningSecretKeyVersion");

                            b1.Property<string>("MaskSuffix")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("SigningSecretMaskSuffix");

                            b1.Property<byte[]>("Nonce")
                                .HasColumnType("bytea")
                                .HasColumnName("SigningSecretNonce");

                            b1.Property<DateTimeOffset?>("RotatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SigningSecretRotatedAt");

                            b1.Property<byte[]>("Tag")
                                .HasColumnType("bytea")
                                .HasColumnName("SigningSecretTag");

                            b1.HasKey("OutboundWebhookEndpointTenantId");

                            b1.ToTable("webhook_endpoints", "integrations");

                            b1.WithOwner()
                                .HasForeignKey("OutboundWebhookEndpointTenantId");
                        });

                    b.Navigation("SigningSecret")
                        .IsRequired();
                });

            modelBuilder.Entity("VibeChat.Notifications.TenantEmailSettings", b =>
                {
                    b.OwnsOne("VibeChat.SharedKernel.EncryptedSecretEnvelope", "SmtpPassword", b1 =>
                        {
                            b1.Property<Guid>("TenantEmailSettingsTenantId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Ciphertext")
                                .HasColumnType("bytea")
                                .HasColumnName("SmtpPasswordCiphertext");

                            b1.Property<short?>("FormatVersion")
                                .HasColumnType("smallint")
                                .HasColumnName("SmtpPasswordFormatVersion");

                            b1.Property<int?>("KeyVersion")
                                .HasColumnType("integer")
                                .HasColumnName("SmtpPasswordKeyVersion");

                            b1.Property<string>("MaskSuffix")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("SmtpPasswordMaskSuffix");

                            b1.Property<byte[]>("Nonce")
                                .HasColumnType("bytea")
                                .HasColumnName("SmtpPasswordNonce");

                            b1.Property<DateTimeOffset?>("RotatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SmtpPasswordRotatedAt");

                            b1.Property<byte[]>("Tag")
                                .HasColumnType("bytea")
                                .HasColumnName("SmtpPasswordTag");

                            b1.HasKey("TenantEmailSettingsTenantId");

                            b1.ToTable("email_settings", "notifications");

                            b1.WithOwner()
                                .HasForeignKey("TenantEmailSettingsTenantId");
                        });

                    b.Navigation("SmtpPassword")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
